apiVersion: apps/v1
kind: Deployment
metadata:

  name: weather-app-deployment-group-6

  namespace: cst8918
  labels:
    app: weather-app-fp6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app-fp6
  template:
    metadata:
      labels:
        app: weather-app-fp6
    spec:
      containers:
        - name: weather-app-container
          image: fp6acr.azurecr.io/weather-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather
                  key: api-key
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
