name: Terraform Validation

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.0.0"

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform

    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1

    - name: Initialize TFLint
      run: tflint --init
      working-directory: terraform

    - name: Run TFLint
      run: tflint --config .tflint.hcl
      working-directory: terraform
