name: Terraform Validation

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.0.0"

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

    - name: Run TFSec
      uses: aquasecurity/tfsec@v1
      with:
        working_dir: terraform
        fail_on_violations: true
        skip_check: "check:tfsec:aws:ec2:EnsureEC2InstanceIsInVPC"

    - name: Run TFLint
      uses: terraform-linters/tflint-action@v2
      with:
        working_directory: terraform
        config_file: .tflint.hcl
